### ISSUE TITLE
[FEAT] 유저가 여러개의 user-service에서 하나의 인스턴스로만 Routing 하는 Sticky Session 구현

### ISSUE THREAD

**Issue by JunHyungJang** [connetist/connectist-backend#103]
## 📕 제목
- 유저가 여러개의 user-service에서 하나의 인스턴스로만 Routing 하는 Sticky Session 구현
## 📔 설명
- 현재 회원가입시에 Certification을 ConcurrentHashMap을 통해서 진행하고 있다
- 이런 경우에, 하나의 유저는 요청을 같은 서버로 해야지 해당 Map의 값을 통해서 인증을 받을 수 있다
- 이를 만족하기 위해서, Load Balancer에서 Cookie 값을 통해서 특정쿠키를 가지는 Request 는 특정 서버로 지속적으로 라우팅 되어야 한다 
1. Custon Load Balancer 구현
```
import org.springframework.cloud.client.ServiceInstance;
import org.springframework.cloud.client.loadbalancer.LoadBalancerClient;
import org.springframework.cloud.gateway.filter.GatewayFilter;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.LoadBalancerClientFilter;
import org.springframework.cloud.gateway.route.Route;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.http.HttpCookie;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import java.util.List;

@Component
@Order(LoadBalancerClientFilter.LOAD_BALANCER_CLIENT_FILTER_ORDER)
public class StickySessionLoadBalancerFilter extends LoadBalancerClientFilter {

    public StickySessionLoadBalancerFilter(LoadBalancerClient loadBalancer) {
        super(loadBalancer);
    }

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        Route route = exchange.getAttribute(GATEWAY_ROUTE_ATTR);
        ServerHttpRequest request = exchange.getRequest();

        String userId = extractUserIdFromRequest(request);
        if (userId != null) {
            ServiceInstance instance = chooseInstance(route.getId(), userId);
            if (instance != null) {
                String uri = instance.getUri().toString();
                ServerHttpRequest newRequest = request.mutate().uri(URI.create(uri)).build();
                return chain.filter(exchange.mutate().request(newRequest).build());
            }
        }
        return chain.filter(exchange);
    }

    private String extractUserIdFromRequest(ServerHttpRequest request) {
        HttpCookie userCookie = request.getCookies().getFirst("userId");
        return userCookie != null ? userCookie.getValue() : null;
    }

    private ServiceInstance chooseInstance(String serviceId, String userId) {
        List<ServiceInstance> instances = loadBalancer.choose(serviceId);
        int index = Math.abs(userId.hashCode() % instances.size());
        return instances.get(index);
    }
}

```
2. 사용자 식별자 추출
- 쿠키에서 userId 추출하기
3. Application.yaml 파일설정
```

spring:
  cloud:
    gateway:
      default-filters:
        - name: StickySessionLoadBalancerFilter
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

```

4. Eureka 설정

```

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

```

## 🏫 To-do
- [ ] Custom LoadBalancer 생성
- [ ] userId 값을 기준으로 Routing
